image: registry.znuny.com/znuny/internal/docker-centos-otrs-systemd:stable

variables:
  MANUAL: ''

include:
  - project: 'Znuny/Internal/Znuny'
    file: '/templates/gitlab/base.yml'

deploy:
  extends: .deploy_stage